spring:
  application:
    name: chatpot-be
  ai:
    vertex:
      ai:
        gemini:
          project-id: ${GEMINI_PROJECT_ID}
          location: asia-northeast3
  datasource:
    url: jdbc:h2:tcp://localhost/~/chatpot
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
