spring:
  application:
    name: chatpot-be
  ai:
    vertex:
      ai:
        gemini:
          project-id: ${GEMINI_PROJECT_ID}
          location: asia-northeast3
  profiles:
    active: local
  cloud:
    aws:
      credentials:
        accessKey: ${S3_ACCESS_KEY}
        secretKey: ${S3_SECRET_KEY}
      region:
        static: ap-northeast-2
      stack:
        auto: false
      s3:
        bucket: chatpot
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
