spring:
  application:
    name: chatpot-be
  profiles:
    active: local
  jpa:
    open-in-view: false
  ai:
    vertex:
      ai:
        gemini:
          project-id: ${GEMINI_PROJECT_ID}
          location: asia-northeast3
  cloud:
    aws:
      credentials:
        accessKey: ${S3_ACCESS_KEY}
        secretKey: ${S3_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: ${S3_BUCKET_NAME}
        folder: ${S3_FOLDER_NAME}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token:
      expired-at: 1800
    refresh-token:
      expired-at: 86400
